[files]
extend-exclude = [".rnw/", "vendor/", "Gemfile.lock", "pnpm-lock.yaml", "*.po", "src/i18n/locales/**", "src/graphql/generated/**", "ios/", "android/", "assets/", "*.svg"]

[default.extend-words]
# add false positives here, one per line, e.g. `ba = "ba"`
unparseable = "unparseable"
ba = "ba"
